src/main/java/edu/iit/sat/itmd4515/tchandr1/fp/domain/Orders.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.tchandr1.fp.domain;

//import one.to.many.bi.*;
//import one.to.many.uni.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
//import one.to.one.bi.Shop;

//import one.to.one.bi.Shop;

/**
 *
 * @author Thanusha
 */
@Entity
@NamedQueries({
  @NamedQuery(name="Orders.findByName" ,query="select o from Orders o where o.orderName= :orderName "),
  @NamedQuery(name="Orders.findById" ,query="select o from Orders o where o.orderId= :orderId"),
  @NamedQuery(name = "Orders.findAll", query = "select o from Orders o")   
})
public class Orders {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long orderId;

    private String orderName;

  @ManyToOne
  @JoinTable(joinColumns = @JoinColumn(name ="orders_orderId" ),
            inverseJoinColumns = @JoinColumn(name="shop_shopId"))
 //  @JoinColumn(name= "ShopOrderId")
   private Shop shop;
  
    @ManyToMany(mappedBy = "orders", cascade = CascadeType.PERSIST)
    private List<Parts> parts =  new ArrayList<>();

    /**
     * Get the value of parts
     *
     * @return the value of parts
     */
    public List<Parts> getParts() {
        return parts;
    }

    /**
     * Set the value of parts
     *
     * @param parts new value of parts
     */
    public void setParts(List<Parts> parts) {
        this.parts = parts;
    }

  
  
/*  @ManyToMany(mappedBy = "orders")
  private Parts part;*/

    /**
     * Get the value of part
     *
     * @return the value of part
     */
  /*  public Parts getPart() {
        return part;
    }*/

    /**
     * Get the value of part
     */
    public Orders() {
    }

    /**
     *
     * @param orderName
     */
    public Orders(String orderName) {
        this.orderName = orderName;
    }

    /**
     *
     * @return
     */
    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    
    /**
     *
     * @return
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     *
     * @param orderName
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     *
     * @return
     */
    public Shop getShop() {
        return shop;
    }

    /**
     *
     * @param shop
     */
    public void setShop(Shop shop) {
        this.shop = shop;
    }

   
    


}

src/main/java/edu/iit/sat/itmd4515/tchandr1/fp/web/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.tchandr1.fp.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author Thanusha
 */
@Named
@RequestScoped
public class LoginBean extends AbstractJSFBean {

    private static final Logger LOG = Logger.getLogger(LoginBean.class.getName());
    @NotNull(message = "You shall not pass without a username!")
    private String username;
    @NotNull(message = "You shall not pass without a password!")
    @Size(min = 5, message = "Password must be at least 5 characters in length.")
    private String password;

    @PostConstruct
    public void postConstruct() {
        super.postContruct();
    }

    public boolean isAdmin() {
        return facesContext.getExternalContext().isUserInRole("admin");
    }

    public boolean isRegularCustomer() {
        return facesContext.getExternalContext().isUserInRole("regularCustomer");
    }

    public boolean isPart() {
        return facesContext.getExternalContext().isUserInRole("part");
    }
    
 

    public String getPortalPathByRole(String path) {
        if (isAdmin()) {
            return "/admin" + path;
        } else if (isPart()) {
            return "/shopPortal" + path;
        } else if (isRegularCustomer()) {
            return "/customerPortal" + path;
        }      
        else {
            return path;
        }
    }

    public String doLogin() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        try {
            req.login(username, password);
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "There has been a problem invoking HttpServletRequest.login", ex);
            facesContext.addMessage(null, new FacesMessage("Bad Login", "Detail: You made a bad login!"));
            return "/login.xhtml";
        }

        // send user to welcome page
        return getPortalPathByRole("/welcome.xhtml?faces-redirect=true");
    }
    
       

    public String getRemoteUser() {
        return facesContext.getExternalContext().getRemoteUser();
    }

    public String doLogout() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        try {
            req.logout();
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "There has been a problem invoking HttpServletRequest.logout", ex);
            facesContext.addMessage(null, new FacesMessage("Bad LogOut", "Detail: You made a bad logout!"));
            return "/login.xhtml";
        }
        return "/login.xhtml";
    }

    /**
     * Get the value of password
     *
     * @return the value of password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the value of password
     *
     * @param password new value of password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Get the value of username
     *
     * @return the value of username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the value of username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    public LoginBean() {
    }

}

src/main/java/edu/iit/sat/itmd4515/tchandr1/fp/web/shop/OrdersBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.tchandr1.fp.web.shop;

import edu.iit.sat.itmd4515.tchandr1.fp.domain.Orders;
import edu.iit.sat.itmd4515.tchandr1.fp.domain.Shop;
import edu.iit.sat.itmd4515.tchandr1.fp.service.OrdersService;
import edu.iit.sat.itmd4515.tchandr1.fp.service.PartsService;
import edu.iit.sat.itmd4515.tchandr1.fp.web.AbstractJSFBean;
import edu.iit.sat.itmd4515.tchandr1.fp.web.LoginBean;
import java.util.List;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Thanusha
 */
@Named
@RequestScoped
public class OrdersBean extends AbstractJSFBean {

    private static final Logger LOG = Logger.getLogger(OrdersBean.class.getName());

    private Orders order;
    private List<Orders> orders;

    @EJB
    private OrdersService ordersService;
    @EJB
    private PartsService partsService;
    @Inject
    LoginBean loginBean;

    public OrdersBean() {
    }
    
    private void refreshShows(){
         orders = partsService.findByUserName(loginBean.getRemoteUser()).getOrders();
    }

    @PostConstruct
    private void postConstruct() {
        super.postContruct();
        order = new Orders();
        order.setShop(new Shop());
       refreshShows();
    }

    public String doDelete(Orders order) {
        LOG.info("The show to delete is " + order.toString());
        ordersService.delete(order,partsService.findByUserName(loginBean.getRemoteUser()));
        refreshShows();
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,null,"Order"+order.getOrderName()+"has been deleted"));
        return loginBean.getPortalPathByRole("/welcome.xhtml");
    }

    public String doUpdate(Orders order) {
        this.order = order;
        LOG.info("The show to update is " + order.toString());
        refreshShows();
        return "/shopPortal/order.xhtml";
    }
    
    public String executeSave() {
    if (this.order.getOrderId() != null) {
        LOG.info("Executing update on " + this.order.toString());
        ordersService.update(order);
        refreshShows();
        return loginBean.getPortalPathByRole("/welcome.xhtml");
    } else {
        LOG.info("Creating " + this.order.toString());
        ordersService.create(order, order.getShop(),partsService.findByUserName(loginBean.getRemoteUser()));
      //  ordersService.create(order);
        refreshShows();
        return loginBean.getPortalPathByRole("/welcome.xhtml");
    }
}

    /**
     * Get the value of orders
     *
     * @return the value of orders
     */
    public List<Orders> getOrders() {
        return orders;
    }

    /**
     * Set the value of orders
     *
     * @param orders new value of orders
     */
    public void setOrders(List<Orders> orders) {
        this.orders = orders;
    }

    /**
     * Get the value of order
     *
     * @return the value of order
     */
    public Orders getOrder() {
        return order;
    }

    /**
     * Set the value of order
     *
     * @param order new value of order
     */
    public void setOrder(Orders order) {
        this.order = order;
    }

}

src/main/webapp/shopPortal/order.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="title">
        #{not empty ordersBean.order.orderId ? "Update Order" : "Create New Order" }
    </ui:define>
    <ui:define name="body">
        <h:form>
            <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="id" value="ORDER ID #{ordersBean.order.orderId}" rendered="#{not empty ordersBean.order.orderId}" />
                    <h:inputHidden id="id" value="#{ordersBean.order.orderId}" />
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="name" value="Name" />
                    <h:inputText p:placeholder="Order Name" id="name" value="#{ordersBean.order.orderName}" />
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="order" value="shop" />
                    <h:selectOneListbox id="orderShop"  value="#{ordersBean.order.shop.shopId}" >
                        <f:selectItems value="#{shopService.findAll()}" var="shop" itemLabel="#{shop.shopName}" itemValue="#{shop.shopId}"/>
                    </h:selectOneListbox>
                </div>
            </div>           
            <div class="row">
                <div class="large-12 columns">
                    <h:commandButton action="#{ordersBean.executeSave()}" class="button expand" value="Save"/>
                </div>
            </div>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/shopPortal/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/portalTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Shop Portal Welcome Page
    </ui:define>

    <ui:define name="body">

        <h:link outcome="order.xhtml" value="Create New Order"/>
        
        <h:dataTable value="#{ordersBean.orders}" var="order">
            <h:column>
                <f:facet name="header"><h:outputText value="ID"/></f:facet>
                <h:outputText value="#{order.orderId}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Name"/></f:facet>
                <h:outputText value="#{order.orderName}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Station"/></f:facet>
                <h:outputText value="#{order.shop.shopName}"/>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{ordersBean.doUpdate(order)}" value="Update"/></h:form>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{ordersBean.doDelete(order)}" value="Delete"/></h:form>
            </h:column>

        </h:dataTable>

        <div class="large-6 columns">
            <ezcomp:partComposite parts="#{partsService.findByUserName(loginBean.remoteUser)}" readonly="true" />
        </div>
        <div class="large-6 columns">
            <ezcomp:partComposite parts="#{partBean.parts}" readonly="false" action="#{partBean.executeUpdate()}"/>
        </div>
    </ui:define>

</ui:composition>