src/main/java/edu/iit/sat/itmd4515/tchandr1/fp/domain/CustomerAddress.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.tchandr1.fp.domain;

//import one.to.one.uni.*;
import edu.iit.sat.itmd4515.tchandr1.fp.domain.security.User;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;

/**
 *
 * @author Thanusha
 */
@Entity
@NamedQueries({
    @NamedQuery(name = "CustomerAddress.findByName", query = "select c from CustomerAddress c where c.customerAddress1= :customerAddress1 "),

    @NamedQuery(name = "CustomerAddress.findById", query = "select c from CustomerAddress c where c.customerId= :customerId"),
    @NamedQuery(name = "CustomerAddress.findAll", query = "select c from CustomerAddress c"),
     @NamedQuery(name = "CustomerAddress.findByUserName",query = "select c from CustomerAddress c where c.user.userName= :userName")
})

public class CustomerAddress  {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long customerId;

    private String customerAddress1;

    private String CustomerAddress2;

    private String city;

    private String state;

    private String country;
    
     @OneToOne
    @JoinColumn(name = "USERNAME")   
    private User user;

    /**
     * Get the value of user
     *
     * @return the value of user
     */
    public User getUser() {
        return user;
    }

    /**
     * Set the value of user
     *
     * @param user new value of user
     */
    public void setUser(User user) {
        this.user = user;
    }


    /**
     *
     */
    public CustomerAddress() {
    }

    /**
     *
     * @param customerAddress1
     * @param CustomerAddress2
     * @param city
     * @param state
     * @param country
     */
    public CustomerAddress(String customerAddress1, String CustomerAddress2, String city, String state, String country) {
        this.customerAddress1 = customerAddress1;
        this.CustomerAddress2 = CustomerAddress2;
        this.city = city;
        this.state = state;
        this.country = country;
    }

    /**
     * Get the value of country
     *
     * @return the value of country
     */
    public String getCountry() {
        return country;
    }

    /**
     * Set the value of country
     *
     * @param country new value of country
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Get the value of state
     *
     * @return the value of state
     */
    public String getState() {
        return state;
    }

    /**
     * Set the value of state
     *
     * @param state new value of state
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Get the value of city
     *
     * @return the value of city
     */
    public String getCity() {
        return city;
    }

    /**
     * Set the value of city
     *
     * @param city new value of city
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Get the value of CustomerAddress2
     *
     * @return the value of CustomerAddress2
     */
    public String getCustomerAddress2() {
        return CustomerAddress2;
    }

    /**
     * Set the value of CustomerAddress2
     *
     * @param CustomerAddress2 new value of CustomerAddress2
     */
    public void setCustomerAddress2(String CustomerAddress2) {
        this.CustomerAddress2 = CustomerAddress2;
    }

    /**
     * Get the value of customerAddress1
     *
     * @return the value of customerAddress1
     */
    public String getCustomerAddress1() {
        return customerAddress1;
    }

    /**
     * Set the value of customerAddress1
     *
     * @param customerAddress1 new value of customerAddress1
     */
    public void setCustomerAddress1(String customerAddress1) {
        this.customerAddress1 = customerAddress1;
    }

    /**
     *
     * @return
     */
    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    
}

src/main/webapp/customerPortal/cust.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        #{not empty customerBean.customer.customerId ? "Update Customer" : "Create New Customer" }
    </ui:define>

    <ui:define name="body">
       
         <h:form>
           <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="customerid" value="CUSTOMER ID #{customerBean.customer.customerId}" rendered="#{not empty customerBean.customer.customerId}" />
                    <h:inputHidden id="customerid" value="#{customerBean.customer.customerId}" />
                </div>
            </div>
             <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="fname" value="Fname" />
                    <h:inputText p:placeholder="FirstName" id="fname" value="#{customerBean.customer.firstName}" required="true" />
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="lname" value="Lname" />
                    <h:inputText p:placeholder="FirstName" id="lname" value="#{customerBean.customer.lastName}" required="true" />
                </div>
            </div>
             <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="customeraddressid" value="CUSTOMER ADDRESS ID #{customerBean.customerAddress.customerId}" rendered="#{not empty customerBean.customerAddress.customerId}" />
                    <h:inputHidden id="customeraddressid" value="#{customerBean.customerAddress.customerId}" />
                </div>
            </div> 
            
            <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="address1" value="Address1" />
                    <h:inputText p:placeholder="CustomerAddress1" id="address1" value="#{customerBean.customerAddress.customerAddress1}" required="true" />
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="address2" value="Address2" />
                    <h:inputText p:placeholder="CustomerAddress2" id="address2" value="#{customerBean.customerAddress.customerAddress2}" required="true"/>
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="city" value="City" />
                    <h:inputText p:placeholder="City" id="city" value="#{customerBean.customerAddress.city}" required="true" />
                </div>
            </div>
             <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="state" value="State" />
                    <h:inputText p:placeholder="State" id="state" value="#{customerBean.customerAddress.state}" required="true"/>
                </div>
            </div>
             <div class="row">
                <div class="large-12 columns">
                    <h:outputLabel for="country" value="Country" />
                    <h:inputText p:placeholder="Country" id="country" value="#{customerBean.customerAddress.country}" required="true"/>
                </div>
            </div>
            
           
             
            
            <div class="row">
                <div class="large-12 columns">
                    <h:commandButton action="#{customerBean.executeSave()}" class="button expand" value="UpdateCustomerDetails"/>
                </div>
            </div>

          
        </h:form>
        
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns ="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
       Welcome to Customer Page
    </ui:define>

    <ui:define name="body">
        
        <h:dataTable value="#{customerBean.findCustomer()}" var="customer">
            <h:column>
                <f:facet name="header"><h:outputText value="ID"/></f:facet>
                <h:outputText value="#{customer.customerId}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="FirstName"/></f:facet>
                <h:outputText value="#{customer.firstName}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="LastName"/></f:facet>
                <h:outputText value="#{customer.lastName}"/>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{customerBean.doUpdate(customer)}" value="Update"/></h:form>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{customerBean.doDelete(customer)}" value="Delete"/></h:form>
            </h:column>

        </h:dataTable>

       
        
    </ui:define>

</ui:composition>